### ISSUE TITLE
[Feedback]: Quick fix after updating to Flutter 3.29.0 for android

### ISSUE THREAD

**Issue by rennylangat** [OneSignal/OneSignal-Flutter-SDK#1011]
### What's on your mind?

In case you have an issue, it has been filed here #984 . The quick fix is this:

``` onesignal_flutter:```
 ```  git:```
  ```   url: https://github.com/milansurelia/OneSignal-Flutter-SDK.git```

PSA: When a new version is release make sure to switch back from the quick fix.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by daniellampl** [comment]
Y'all can also use the version that will be shipped eventually:

`
  onesignal_flutter:
    git:
      url: https://github.com/OneSignal/OneSignal-Flutter-SDK.git
      ref: "df09f09c754e93438bbe3975f12f2f4649f81cd3"`

**Comment by daniellampl** [comment]
You can also use the fix that will be shipped eventually:

```yaml
onesignal_flutter:
  git:
    url: https://github.com/OneSignal/OneSignal-Flutter-SDK.git
    ref: "df09f09c754e93438bbe3975f12f2f4649f81cd3"
```

@jkasten2, is there an estimated timeline for publishing this critical fix on pub.dev?
