### ISSUE TITLE
Builds fail when using OneSignal and FlutterYoutube

### ISSUE THREAD

**Issue by jeffmikels** [OneSignal/OneSignal-Flutter-SDK#22]
**Description:**

After following the OneSignal setup guide (creating the Notification Service Extension) subsequent ios builds fail with the following error:

```
$ flutter build ios

Building org.jeffmikels.innovation.OneSignalNotificationServiceExtension for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: R82H62YSB3
Starting Xcode build...                                          
Xcode build done.                                            1.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Pods-Runner OF PROJECT Pods WITH CONFIGURATION Release ===
    ld: '/Volumes/Jeff/Development/@Flutter/church_app_flutter/org.jeffmikels.innovation/build/ios/Release-iphoneos/XCDYouTubeKit/libXCDYouTubeKit.a(XCDYouTubeClient.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Volumes/Jeff/Development/@Flutter/church_app_flutter/org.jeffmikels.innovation/build/ios/Release-iphoneos/XCDYouTubeKit/libXCDYouTubeKit.a' for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ld: '/Volumes/Jeff/Development/@Flutter/church_app_flutter/org.jeffmikels.innovation/build/ios/Release-iphoneos/XCDYouTubeKit/libXCDYouTubeKit.a(XCDYouTubeClient.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Volumes/Jeff/Development/@Flutter/church_app_flutter/org.jeffmikels.innovation/build/ios/Release-iphoneos/XCDYouTubeKit/libXCDYouTubeKit.a' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Encountered error while building for device.
```

**Environment**

**Steps to Reproduce Issue:**

1. create any flutter app.
2. specify flutter_youtube and onesignal in the pubspec.yaml
3. `flutter build ios` works
4. Follow the setup guide for iOS to create Notification Service Extension.
5. `flutter build ios` fails

**Comment by jeffmikels** [comment]
No changes have been made to any file other than adding these two libraries to the pubspec.yaml.

Here's proof:

full pubspec

```
name: t3
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flutter_youtube: ^1.1.1
  onesignal: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```

full Podfile

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
