### ISSUE TITLE
Conflict with others packages that depends from newer Play Services package

### ISSUE THREAD

**Issue by vinicioslc** [OneSignal/OneSignal-Flutter-SDK#27]
**Description:**

There is an incompatibility with some plugins that manage geolocation probably because of the outdated version of GooglePlay services used in onesignal as a dependency.

Simply add the [onesignal](https://pub.dartlang.org/packages/onesignal) package to [geolocator](https://github.com/BaseflowIT/flutter-geolocator) sample project, configure correctly the two packages, and run on a device and BOOM the trick happens
the app crashes on startup...

**Environment**

**Steps to Reproduce Issue:**

 
1. Clone the example project from [geolocator](https://github.com/BaseflowIT/flutter-geolocator)
2. Add latest one signal package to the project.
3. Run application in any *Android* device..
4. See the app closes before it opens
my pubspec...
```
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  onesignal: ^1.0.2
  geolocator: ^2.0.1
```

**Anything else:**

(crash stacktraces, as well as any other information here)

In this issue you have information about logcat, [Link to issue](https://github.com/BaseflowIT/flutter-geolocator/issues/124#event-1890065698)
