### ISSUE TITLE
Build Error - Requires a placeholder substitution but no value for <onesignal_google_project_number> and <onesignal_app_id>

### ISSUE THREAD

**Issue by danielgomezrico** [OneSignal/OneSignal-Flutter-SDK#324]
# Versions
```YAML
environment:
  sdk: 2.10.4
  flutter: 1.22.4

dependencies:
-   onesignal_flutter: 2.6.2 and 2.6.1
```

# Description
Error:

```bash
mypath/android/app/src/main/AndroidManifest.xml:49:9-51:51 Error:
        Attribute meta-data#onesignal_app_id@value at AndroidManifest.xml:49:9-51:51 requires a placeholder substitution but no value for <onesignal_app_id> is provided.
mypath/android/app/src/main/AndroidManifest.xml:53:9-55:70 Error:
        Attribute meta-data#onesignal_google_project_number@value at AndroidManifest.xml:53:9-55:70 requires a placeholder substitution but no value for <onesignal_google_project_number> is provided.

FAILURE: Build failed with an exception.
```

This happens after trying:

```bash
flutter build appbundle --release

// Or
flutter build apk --release
```
