### ISSUE TITLE
OneSignal Flutter v2.6.2 not working with Firebase Cloud Messaging 8.0.0-dev.14

### ISSUE THREAD

**Issue by davidbrenner** [OneSignal/OneSignal-Flutter-SDK#348]
**Description:**

OneSignal Flutter v2.6.2 not working with Firebase Cloud Messaging 8.0.0-dev.14

**Environment**

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: "0.7.0"
  firebase_analytics: "^7.0.1"
  firebase_auth: "^0.20.0+1"
  firebase_crashlytics: "^0.4.0+1"
  firebase_messaging: "^8.0.0-dev.14"
  cloud_firestore: "^0.16.0"
  firebase_dynamic_links: ^0.7.0+1
  firebase_in_app_messaging: "^0.3.0+1"
  firebase_storage: "^7.0.0"
  onesignal_flutter: ^2.6.2
```

```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Steps to Reproduce Issue:**

1. Start with project with working FCM
1. Install OneSiganal Flutter SDK following these instructions: https://documentation.onesignal.com/docs/flutter-sdk-setup
1. Attempt to receive a push notification to a physical iOS device sent via FCM console

The message is received, but the FCM handlers are not called when the message is opened. Before installing OneSignal, this was working. Additionally, FCM was working with OneSignal on older builds of this app. As part of tracking down this issue, I created a new project and added anything involving notification-related code step-by-step. Once OneSignal was added and configured, FCM's handling broke. 

We use both OneSignal and FCM APIs separately, but FCM is far more important to us than OneSignal, so our solution is going to be to just remove OneSignal. We would still like to use it if there is a solution.

**Anything else:**

N/A
