### ISSUE TITLE
MissingPluginException(No implementation found for method OneSignal#setInFocusDisplayType on channel OneSignal)

### ISSUE THREAD

**Issue by giusepetroso** [OneSignal/OneSignal-Flutter-SDK#379]
**Description:**

Hi, I just moved an old project lib folder to a new project due to flutter message of android deprecation:
![image](https://user-images.githubusercontent.com/17656277/114522400-a6327a80-9c43-11eb-9e76-93e721125518.png)

After the creation of the new project I copied the lib folder from old proj, and ran it into android device.

Compiling is ok but at runtime this kind of exceptions appeared:
![image](https://user-images.githubusercontent.com/17656277/114523481-99faed00-9c44-11eb-806e-e342927a612a.png)

I tried to do `flutter clean` and `flutter pub get` again.
I tried to erase **android** folder, generating another one in a new project with the same name and replace into my project, but nothing happened.

I don't know what to do.

**Environment**

This is my **flutter doctor**:
```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Versione 10.0.19042.867], locale it-IT)
    • Flutter version 2.0.4 at C:\Users\gpetr\AppData\Local\Flutter
    • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2) 
    • Android SDK at C:\Users\gpetr\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\gpetr\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\gpetr\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.55.1)
    • VS Code at C:\Users\gpetr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • moto g 9 plus (mobile) • ZY227V96VC • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)             • edge       • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```

This is my **pubspec.yaml**:
```
name: comfortparcel_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_verification_code_input:
    git:
      url: git://github.com/tiny-express/flutter_verification_code_input

  cupertino_icons: ^1.0.2
  flutter_bloc: ^3.0.0
  meta: ^1.1.6
  equatable: ^0.6.0
  http: ^0.12.0+2
  shared_preferences: ^2.0.0
  flutter_facebook_login: ^3.0.0
  rxdart: ^0.23.0
  provider: ^4.0.0
  intl_phone_number_input: ^0.2.0
  flutter_swiper: ^1.1.6
  flutter_datetime_picker: ^1.4.0
  grouped_buttons: ^1.0.3
  image_picker: ^0.6.5
  onesignal_flutter: ^2.0.0
  url_launcher: ^5.2.7
  barcode_scan: ^2.0.2
  intl: ^0.17.0
  pull_to_refresh: ^1.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - locale/i18n_en.json
    - locale/i18n_it.json
    - assets/images/background.png
    - assets/images/splash_background.png
    - assets/images/box_background.png
    - assets/images/img_host.png
    - assets/images/img_home.png
    - assets/images/img_qr_scan.png
    - assets/images/img_qr_scan_arrow.png
    - assets/images/img_qr_scan_enter.png
    - assets/images/img_keys.png

  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Bold.ttf
        - asset: assets/fonts/Oxygen-Light.ttf
        - asset: assets/fonts/Oxygen-Regular.ttf
```

**Steps to Reproduce Issue:**

1. flutter create a new project
2. copy lib folder from other project
3 paste android onesignal gradle plugin lines (from https://documentation.onesignal.com/docs/flutter-sdk-setup) into build.gradle
4. flutter pub get
5. run
