### ISSUE TITLE
Error java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient when I open a notification

### ISSUE THREAD

**Issue by GiacomoK** [OneSignal/OneSignal-Flutter-SDK#60]
**Description:**
I implemented this plugin and it works, but in the debug console I get this error when I open a notification:

    Error getting Google Ad id:
    I/OneSignal(17403): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient;
    I/OneSignal(17403): 	at com.onesignal.AdvertisingIdProviderGPS.getIdentifier(AdvertisingIdProviderGPS.java:45)
    I/OneSignal(17403): 	at com.onesignal.OneSignal.registerUserTask(OneSignal.java:1223)
    I/OneSignal(17403): 	at com.onesignal.OneSignal.access$2300(OneSignal.java:80)
    I/OneSignal(17403): 	at com.onesignal.OneSignal$7.run(OneSignal.java:1206)
    I/OneSignal(17403): 	at java.lang.Thread.run(Thread.java:762)
    I/OneSignal(17403): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.identifier.AdvertisingIdClient" on path: DexPathList[[zip file "/data/app/com.example-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example-2/lib/arm, /data/app/com.example-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
    I/OneSignal(17403): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    I/OneSignal(17403): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    I/OneSignal(17403): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

The notification is opened correctly, but I do not know what this error means or if its serious.

**Steps to Reproduce Issue:**

  1. Install the OneSignal Flutter SDK using pub into your project
  2. Initialize the SDK using OneSignal.shared.init(your_app_id)
  3. Attempt to receive a push notification

**Comment by rgomezp** [comment]
I am not familiar with this error. The error mentions Google Ad id. Is this something you are using in your project?

**Comment by SiebeVE** [comment]
I'm receiving the error as well. Downgrading to for now `1.0.3` does the trick for me.

**Comment by GiacomoK** [comment]
@rgomezp 
> I am not familiar with this error. The error mentions Google Ad id. Is this something you are using in your project?

No, thats the problem

@SiebeVE I will try to downgrade and I'll let you know. Thanks.

**Comment by GiacomoK** [comment]
Nothing, I tried with 1.0.3, 1.0.4 and I get same error.

**Comment by rgomezp** [comment]
@SiebeVE @GiacomoK Can you try to reproduce this issue in a different project? Feel free to include your gradle file. It's possible this could be arising from a conflict with another plugin. Our SDK is not the root of the issue, but the fact our SDK cannot find the class is probably an indication of a larger problem with the Google Play Services library (you may have messed up your dependencies)

**Comment by SiebeVE** [comment]
These are my configs. I will try to reproduce it in a new project.

Thanks!

pubspec.yaml
```
name: myApp
description: MyApp
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: any
  shared_preferences: ^0.4.3
  url_launcher: ^4.0.1
  geolocator: ^2.1.1
  onesignal: 1.0.3
  http: ^0.12.0+1
  connectivity: ^0.4.0+1
  intl: ^0.15.7
  cached_network_image: ^0.5.1
  permission_handler: 2.1.2
  device_info: ^0.4.0+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/border/
  fonts:
    - family: Branding
      fonts:
       - asset: assets/fonts/leafy.woff
    - family: IconFont
      fonts:
       - asset: assets/fonts/icon-font.ttf
```

android/app/build.gradle
```
buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.2, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 27

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "***"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 6
        versionName "0.4.0-beta"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            useProguard false

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```
