### ISSUE TITLE
question of deep links. open the app,then click mobile's back button to home, recieved a notifation message with additional data({'link': 'xxx'}), click the notifation message, mobile relaunch the app,but can't call the NotificationOpenedHandler.

### ISSUE THREAD

**Issue by telinx** [OneSignal/OneSignal-Flutter-SDK#97]
sdk document:
```
setNotificationOpenedHandler
METHOD
This function/callback will be called whenever a user taps on a OneSignal push notification from your application.
If your application was closed and the user taps a notification, the app will launch, and the SDK will call this handler.
```

onesignal: ^1.1.0
### pubspec.yaml:
```
name: celestyles_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  lpinyin: ^1.0.7
  common_utils: ^1.1.1
  flustars: 0.2.5
  fluintl: ^0.1.2
  # azlistview: ^0.1.0
  dio: ^1.0.13
  rxdart: ^0.21.0
  cached_network_image: ^0.8.0
  flutter_advanced_networkimage: any
  url_launcher: ^5.0.2
  pull_to_refresh: 1.1.6
  device_info: ^0.4.0+1
  webview_flutter: ^0.3.4
  flukit: ^1.0.0
  fluro: ^1.4.0
  parallax_image: ^0.3.1+1
  open_iconic_flutter: ">=0.3.0 <0.4.0"
  video_player: ">=0.7.0 <0.11.0"
  # chewie: ^0.9.7 
  screen: ">=0.0.4 <0.1.0"
  # giffy_dialog: ^1.3.0
  fluttertoast: ^3.1.0
  tip_dialog: ^2.0.0
  flutter_spinkit: ^3.1.0
  event_bus: ^1.1.0
  # firebase_core: ^0.4.0
  # firebase_auth: 0.8.0
  # firebase_dynamic_links: ^0.3.0
  
  flutter_facebook_login:
    git: 
      url: https://github.com/AnyKindaApp/flutter_facebook_login.git
      ref: fbloginkit-fix
  # flutter_facebook_login: ^2.0.0
  # facebook_share: ^0.0.1+3
  share_extend: ^1.0.8
  # image_downloader: ^0.15.2
  
  google_sign_in: ^4.0.1+3
  onesignal: ^1.1.0
  uni_links: ^0.1.4

  # chewie: ^0.9.7
  connectivity: ^0.4.3+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/ali_connors.png
    - assets/images/ali_connors_sml.png
    - assets/images/qrcode.png
    - assets/images/icon_dumei_android.png
    - assets/images/ic_launcher_news.png
    - assets/images/guide1.png
    - assets/images/guide2.png
    - assets/images/guide3.png
    - assets/images/guide4.png
    - assets/images/splash_bg.png
    - assets/images/3.0x/airplane.png
    - assets/images/avatar_default.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/twitter.png
    - assets/images/placeholder-avata.png
    - assets/data/china.json

  
```
 

### environment:
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/yucang/git/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/yucang/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/yucang/software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/yucang/software/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.34.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • Redmi 6A • 8835d2d87d25 • android-arm • Android 8.1.0 (API 27)
```

### main_page.dart:
```
import 'dart:async';

import 'package:celestyles_app/common/sp_helper.dart';
import 'package:celestyles_app/data/protocol/models.dart';
import 'package:celestyles_app/ui/config/route_index.dart';
import 'package:celestyles_app/ui/widgets/widgets.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';

import 'package:celestyles_app/blocs/bloc_index.dart';
import 'package:celestyles_app/common/common.dart';
import 'package:celestyles_app/ui/pages/recommend/for_you_page.dart';
import 'package:celestyles_app/ui/widgets/bottom_navi_bar.dart';
import 'package:celestyles_app/utils/util_index.dart';
import 'package:connectivity/connectivity.dart';

import 'package:flutter/material.dart';
import 'package:onesignal/onesignal.dart';
import 'package:rxdart/rxdart.dart';
import 'home/home_page.dart';

class MainPage extends StatefulWidget {

  MainPage({Key key}): super(key: key);

  @override
  _MainPageState createState() => _MainPageState();

}
class _MainPageState extends State<MainPage> {

  ...
  ///--------------------------OneSignal Param Begin-------------------------///
  String _debugLabelString = "";
  bool _requireConsent = false;   // CHANGE THIS parameter to true if you want to test GDPR privacy consent
  ///--------------------------OneSignal Param end-------------------------///

  @override
  initState(){
    super.initState();
    // ...
    initOneSignal();            // initial OneSignal
  }

  ///-------------------------OneSignal Begin---------------------------///
  Future<void> initOneSignal() async  {
    if (!mounted) return;
    LogUtil.e("2...initOneSignal===================================>>>>>>>>>>>>");
    OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);

    OneSignal.shared.setRequiresUserPrivacyConsent(_requireConsent);

    OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {
      LogUtil.e("2...OPENED NOTIFICATION===================================>>>>>>>>>>>>");
      LogUtil.e('===========>>>>>>>>>>>>' + result.notification.jsonRepresentation().replaceAll("\\n", "\n"));
      dynamic link = result.notification.payload.additionalData['link'];
      if(null != link){
        String parse = link.replaceFirst("http://aidumei.com/us/", "");
        LogUtil.e("2...LINK IS --------->>>>>>>>>>$link");
        LogUtil.e("2...AFTER PARSE IS --------->>>>>>>>>>$parse");
        this._notifacationForward(parse);
      }
    });

    OneSignal.shared.setSubscriptionObserver((OSSubscriptionStateChanges changes) {
      LogUtil.e("SUBSCRIPTION STATE CHANGED: ${changes.jsonRepresentation()}");
    });

    OneSignal.shared.setPermissionObserver((OSPermissionStateChanges changes) {
      LogUtil.e("PERMISSION STATE CHANGED: ${changes.jsonRepresentation()}");
    });

    OneSignal.shared.setEmailSubscriptionObserver((OSEmailSubscriptionStateChanges changes) {
      LogUtil.e("EMAIL SUBSCRIPTION STATE CHANGED ${changes.jsonRepresentation()}");
    });

    OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.notification);

    OneSignal.shared.promptUserForPushNotificationPermission(fallbackToSettings: true);

    OneSignal.shared.init(
        AppConfig.oneSignalAppId,
        iOSSettings: {
          OSiOSSettings.autoPrompt: false,
          OSiOSSettings.inAppLaunchUrl : true
        }
    );
  }

  void _notifacationForward(String parse){
    LogUtil.e("_notifacationForward --------->>>>>>>>>>begin-->");
    List<String> links = parse.split("/");
    if(parse.indexOf('article')>= 0){
       this._goArticleDetail(context, links[1]);
    }
  }

  void _goArticleDetail(BuildContext context, String id) {
    LogUtil.e("_goArticleDetail --------->>>>>>>>>>begin-->" + '${Routes.mainArticleDetail}?labelId=${AppLocalLabel.homeDetailPage}&articleId=$id');
    Navigator.of(context).push(
       CupertinoPageRoute(
         builder: (context) {
           return Scaffold(
             body: Center(
               child: Text('---go--->>>>>$id'),
             ),
           );
         },
       ),
     );
    NavigatorUtil.pushPage(context, MainArticleDetailPage(labelId: AppLocalLabel.homeDetailPage, articleId: id));
  }

  // ...  

  @override
  void dispose() {
    super.dispose();
  }
}
```

question of deep links. open the app,then click mobile's back button to home, recieved a notifation message with additional data({'link': 'xxx'}), click the notifation message, mobile launch the app,but can't call the NotificationOpenedHandler.
